### ISSUE TITLE
Nothing happens when you install

### ISSUE THREAD

**Issue by IlgazC** [UnitedRPMs/broadcom-wl-dkms#3]
I have the worst possible 43142 variant claimed to be supported by "wl" module but didn't work at all. So I switched to the dkms version.

This PC has this wireless (it is a HP Pavillion x360)
03:00.0 Network controller: Broadcom Inc. and subsidiaries BCM43142 802.11b/g/n (rev 01)
	DeviceName: Broadcom BCM43142 802.11bgn 1x1 WiFi Adapter + BT 4.0 combo adapter
	Subsystem: Hewlett-Packard Company Device 2230
	Flags: bus master, fast devsel, latency 0
	Memory at c1100000 (64-bit, non-prefetchable) [size=32K]
	Capabilities: <access denied>
	Kernel modules: wl

I did every trick, even the interesting "disable safe mode". It doesn't appear to be working at all, worse thing is Broadcom/Network manager seems to crash the kernel on every login without too much info. As this driver is directly from Broadcom, we shouldn't need any firmware cutter etc right? How can I make sure it is loaded?

**Comment by kuboosoft** [comment]
@IlgazC Hi. Badly in Fedora since F30 we have problems with the module... We are not priority for wpa_supplicant update in Fedora... Then the solution (it fails constantly) [here](https://fedoraproject.org/wiki/Common_F30_bugs#Broadcom_wireless_adapters_using_proprietary_broadcom-wl_driver_do_not_work_reliably).

**Comment by kuboosoft** [comment]
https://github.com/UnitedRPMs/wpa_supplicant/blob/master/wpa_supplicant.spec#L189
